name: ci

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Short SHA
        uses: benjlevesque/short-sha@v2.1
        id: short-sha

      - name: Set Repository Name to Lowercase
        uses: ASzc/change-string-case-action@v5
        id: repo-tolower
        with:
          string: ${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ steps.repo-tolower.outputs.lowercase }}:${{ steps.short-sha.outputs.sha }}
            ghcr.io/${{ steps.repo-tolower.outputs.lowercase }}:latest
